services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgres/data
